from tkinter import *
from tkinter import messagebox
from translate import Translator
def french():
    query=frame1.get()
    translator=Translator(to_lang="fr")
    translation=translator.translate(query)
    frame2.insert(0,translation)
def arebic():
    query=frame1.get()
    translator=Translator(to_lang="ar")
    translation=translator.translate(query)
    frame3.insert(0,translation)
def urdu():
    query=frame1.get()
    translator=Translator(to_lang="ur")
    translation=translator.translate(query)
    frame4.insert(0,translation)
def hindi():
    query=frame1.get()
    translator=Translator(to_lang="hi")
    translation=translator.translate(query)
    frame5.insert(0,translation)
def kannada():
    query=frame1.get()
    translator=Translator(to_lang="kn")
    translation=translator.translate(query)
    frame6.insert(0,translation)
def tiefunc():
    french()
    arebic()
    urdu()
    hindi()
    kannada()
def clear():
    frame1.delete(0,END)
    frame2.delete(0,END)
    frame3.delete(0,END)
    frame4.delete(0,END)
    frame5.delete(0,END)
    frame6.delete(0,END)
root=Tk()
root.configure(background="purple")
root.geometry("500x650")
root.title("Language translator")
root.resizable(0,0)
label1=Label(root,text="LANGUAGE TRANSLATOR",bg="pink",fg="purple",height="3",width="40",font=("arial",15,"bold"))
label1.grid(row=0,column=0,padx=10,pady=10)
label2=Label(root,text="Enter statement in English:",bg="white",fg="green")
label2.grid(row=1,column=0,padx=10,pady=10)                                                                     
frame1=Entry(root,width=60)
frame1.grid(row=2,column=0,padx=10,pady=10)
button1=Button(root,text="TRANSLATE",width="10",height="1",command=tiefunc)
button1.grid(row=3,column=0,padx=1,pady=1)
label3=Label(root,text="Translation in French:",bg="green",fg="white")
label3.grid(row=5,column=0,padx=10,pady=10)
frame2=Entry(root,width=60)
frame2.grid(row=6,column=0,padx=10,pady=10)
label4=Label(root,text="Translation in Arebic:",bg="green",fg="white")
label4.grid(row=7,column=0,padx=10,pady=10)
frame3=Entry(root,width=60)
frame3.grid(row=8,column=0,padx=10,pady=10)
label5=Label(root,text="Translation in Urdu:",bg="green",fg="white")
label5.grid(row=9,column=0,padx=10,pady=10)
frame4=Entry(root,width=60)
frame4.grid(row=10,column=0,padx=10,pady=10)
label6=Label(root,text="Translation in Hindi:",bg="green",fg="white")
label6.grid(row=11,column=0,padx=10,pady=10)
frame5=Entry(root,width=60)
frame5.grid(row=12,column=0,padx=10,pady=10)
label7=Label(root,text="Translation in Kannada:",bg="green",fg="white")
label7.grid(row=13,column=0,padx=10,pady=10)
frame6=Entry(root,width=60)
frame6.grid(row=14,column=0,padx=10,pady=10)
button2=Button(root,text="CLEAR",height="1",width="10",command=clear)
button2.grid(row=15,column=0,padx=10,pady=10)
root.mainloop()
